//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary.AcctService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyRateConversionUrlInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CurrencyRateConversionUrlInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString URLsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfInt IDsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString NamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString DescriptionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ModelLibrary.AcctService.ArrayOfString URLs {
            get {
                return this.URLsField;
            }
            set {
                if ((object.ReferenceEquals(this.URLsField, value) != true)) {
                    this.URLsField = value;
                    this.RaisePropertyChanged("URLs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ModelLibrary.AcctService.ArrayOfInt IDs {
            get {
                return this.IDsField;
            }
            set {
                if ((object.ReferenceEquals(this.IDsField, value) != true)) {
                    this.IDsField = value;
                    this.RaisePropertyChanged("IDs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ModelLibrary.AcctService.ArrayOfString Names {
            get {
                return this.NamesField;
            }
            set {
                if ((object.ReferenceEquals(this.NamesField, value) != true)) {
                    this.NamesField = value;
                    this.RaisePropertyChanged("Names");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ModelLibrary.AcctService.ArrayOfString Descriptions {
            get {
                return this.DescriptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionsField, value) != true)) {
                    this.DescriptionsField = value;
                    this.RaisePropertyChanged("Descriptions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentTerm", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PaymentTerm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString SearchKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfBoolean ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfBoolean DefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfBoolean FixedDueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfBoolean AfterDeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfBoolean NextBusinessDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfInt1 FixMonthDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfInt1 FixMonthCutOffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfInt1 FixMonthOffsetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfInt NetDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString NetDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfInt DiscountDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfInt DiscountDay2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfDecimal DiscountPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfDecimal DiscountPercentage2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfInt GraceDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString DocNoteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ModelLibrary.AcctService.ArrayOfString Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ModelLibrary.AcctService.ArrayOfString Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ModelLibrary.AcctService.ArrayOfString SearchKey {
            get {
                return this.SearchKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchKeyField, value) != true)) {
                    this.SearchKeyField = value;
                    this.RaisePropertyChanged("SearchKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ModelLibrary.AcctService.ArrayOfBoolean Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveField, value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ModelLibrary.AcctService.ArrayOfBoolean Default {
            get {
                return this.DefaultField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultField, value) != true)) {
                    this.DefaultField = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ModelLibrary.AcctService.ArrayOfBoolean FixedDueDate {
            get {
                return this.FixedDueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.FixedDueDateField, value) != true)) {
                    this.FixedDueDateField = value;
                    this.RaisePropertyChanged("FixedDueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ModelLibrary.AcctService.ArrayOfBoolean AfterDelivery {
            get {
                return this.AfterDeliveryField;
            }
            set {
                if ((object.ReferenceEquals(this.AfterDeliveryField, value) != true)) {
                    this.AfterDeliveryField = value;
                    this.RaisePropertyChanged("AfterDelivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public ModelLibrary.AcctService.ArrayOfBoolean NextBusinessDay {
            get {
                return this.NextBusinessDayField;
            }
            set {
                if ((object.ReferenceEquals(this.NextBusinessDayField, value) != true)) {
                    this.NextBusinessDayField = value;
                    this.RaisePropertyChanged("NextBusinessDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public ModelLibrary.AcctService.ArrayOfInt1 FixMonthDay {
            get {
                return this.FixMonthDayField;
            }
            set {
                if ((object.ReferenceEquals(this.FixMonthDayField, value) != true)) {
                    this.FixMonthDayField = value;
                    this.RaisePropertyChanged("FixMonthDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public ModelLibrary.AcctService.ArrayOfInt1 FixMonthCutOff {
            get {
                return this.FixMonthCutOffField;
            }
            set {
                if ((object.ReferenceEquals(this.FixMonthCutOffField, value) != true)) {
                    this.FixMonthCutOffField = value;
                    this.RaisePropertyChanged("FixMonthCutOff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public ModelLibrary.AcctService.ArrayOfInt1 FixMonthOffset {
            get {
                return this.FixMonthOffsetField;
            }
            set {
                if ((object.ReferenceEquals(this.FixMonthOffsetField, value) != true)) {
                    this.FixMonthOffsetField = value;
                    this.RaisePropertyChanged("FixMonthOffset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public ModelLibrary.AcctService.ArrayOfInt NetDays {
            get {
                return this.NetDaysField;
            }
            set {
                if ((object.ReferenceEquals(this.NetDaysField, value) != true)) {
                    this.NetDaysField = value;
                    this.RaisePropertyChanged("NetDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public ModelLibrary.AcctService.ArrayOfString NetDay {
            get {
                return this.NetDayField;
            }
            set {
                if ((object.ReferenceEquals(this.NetDayField, value) != true)) {
                    this.NetDayField = value;
                    this.RaisePropertyChanged("NetDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public ModelLibrary.AcctService.ArrayOfInt DiscountDay {
            get {
                return this.DiscountDayField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountDayField, value) != true)) {
                    this.DiscountDayField = value;
                    this.RaisePropertyChanged("DiscountDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public ModelLibrary.AcctService.ArrayOfInt DiscountDay2 {
            get {
                return this.DiscountDay2Field;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountDay2Field, value) != true)) {
                    this.DiscountDay2Field = value;
                    this.RaisePropertyChanged("DiscountDay2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public ModelLibrary.AcctService.ArrayOfDecimal DiscountPercentage {
            get {
                return this.DiscountPercentageField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountPercentageField, value) != true)) {
                    this.DiscountPercentageField = value;
                    this.RaisePropertyChanged("DiscountPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public ModelLibrary.AcctService.ArrayOfDecimal DiscountPercentage2 {
            get {
                return this.DiscountPercentage2Field;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountPercentage2Field, value) != true)) {
                    this.DiscountPercentage2Field = value;
                    this.RaisePropertyChanged("DiscountPercentage2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public ModelLibrary.AcctService.ArrayOfInt GraceDay {
            get {
                return this.GraceDayField;
            }
            set {
                if ((object.ReferenceEquals(this.GraceDayField, value) != true)) {
                    this.GraceDayField = value;
                    this.RaisePropertyChanged("GraceDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public ModelLibrary.AcctService.ArrayOfString DocNote {
            get {
                return this.DocNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.DocNoteField, value) != true)) {
                    this.DocNoteField = value;
                    this.RaisePropertyChanged("DocNote");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBoolean", Namespace="http://tempuri.org/", ItemName="boolean")]
    [System.SerializableAttribute()]
    public class ArrayOfBoolean : System.Collections.Generic.List<bool> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt1", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt1 : System.Collections.Generic.List<System.Nullable<int>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDecimal", Namespace="http://tempuri.org/", ItemName="decimal")]
    [System.SerializableAttribute()]
    public class ArrayOfDecimal : System.Collections.Generic.List<decimal> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxMgmt", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TaxMgmt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfBoolean ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfBoolean DefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfInt TaxCategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.TaxCategory TaxCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfBoolean TaxExemptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfBoolean RequiresTaxCertificateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfBoolean DocumentLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfBoolean SalesTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfBoolean SummaryLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfInt Parent_Tax_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString SOPOTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfDecimal RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString TaxIndicatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfInt C_Country_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfInt To_Country_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfInt C_Region_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfInt To_Region_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ModelLibrary.AcctService.ArrayOfString Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ModelLibrary.AcctService.ArrayOfString Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ModelLibrary.AcctService.ArrayOfBoolean Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveField, value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ModelLibrary.AcctService.ArrayOfBoolean Default {
            get {
                return this.DefaultField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultField, value) != true)) {
                    this.DefaultField = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ModelLibrary.AcctService.ArrayOfInt TaxCategoryID {
            get {
                return this.TaxCategoryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxCategoryIDField, value) != true)) {
                    this.TaxCategoryIDField = value;
                    this.RaisePropertyChanged("TaxCategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ModelLibrary.AcctService.TaxCategory TaxCategory {
            get {
                return this.TaxCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxCategoryField, value) != true)) {
                    this.TaxCategoryField = value;
                    this.RaisePropertyChanged("TaxCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ModelLibrary.AcctService.ArrayOfBoolean TaxExempt {
            get {
                return this.TaxExemptField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxExemptField, value) != true)) {
                    this.TaxExemptField = value;
                    this.RaisePropertyChanged("TaxExempt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public ModelLibrary.AcctService.ArrayOfBoolean RequiresTaxCertificate {
            get {
                return this.RequiresTaxCertificateField;
            }
            set {
                if ((object.ReferenceEquals(this.RequiresTaxCertificateField, value) != true)) {
                    this.RequiresTaxCertificateField = value;
                    this.RaisePropertyChanged("RequiresTaxCertificate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public ModelLibrary.AcctService.ArrayOfBoolean DocumentLevel {
            get {
                return this.DocumentLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentLevelField, value) != true)) {
                    this.DocumentLevelField = value;
                    this.RaisePropertyChanged("DocumentLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public ModelLibrary.AcctService.ArrayOfBoolean SalesTax {
            get {
                return this.SalesTaxField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesTaxField, value) != true)) {
                    this.SalesTaxField = value;
                    this.RaisePropertyChanged("SalesTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public ModelLibrary.AcctService.ArrayOfBoolean SummaryLevel {
            get {
                return this.SummaryLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryLevelField, value) != true)) {
                    this.SummaryLevelField = value;
                    this.RaisePropertyChanged("SummaryLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public ModelLibrary.AcctService.ArrayOfInt Parent_Tax_ID {
            get {
                return this.Parent_Tax_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Parent_Tax_IDField, value) != true)) {
                    this.Parent_Tax_IDField = value;
                    this.RaisePropertyChanged("Parent_Tax_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public ModelLibrary.AcctService.ArrayOfString SOPOType {
            get {
                return this.SOPOTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SOPOTypeField, value) != true)) {
                    this.SOPOTypeField = value;
                    this.RaisePropertyChanged("SOPOType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public ModelLibrary.AcctService.ArrayOfDecimal Rate {
            get {
                return this.RateField;
            }
            set {
                if ((object.ReferenceEquals(this.RateField, value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public ModelLibrary.AcctService.ArrayOfString TaxIndicator {
            get {
                return this.TaxIndicatorField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxIndicatorField, value) != true)) {
                    this.TaxIndicatorField = value;
                    this.RaisePropertyChanged("TaxIndicator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public ModelLibrary.AcctService.ArrayOfInt C_Country_ID {
            get {
                return this.C_Country_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.C_Country_IDField, value) != true)) {
                    this.C_Country_IDField = value;
                    this.RaisePropertyChanged("C_Country_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public ModelLibrary.AcctService.ArrayOfInt To_Country_ID {
            get {
                return this.To_Country_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.To_Country_IDField, value) != true)) {
                    this.To_Country_IDField = value;
                    this.RaisePropertyChanged("To_Country_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public ModelLibrary.AcctService.ArrayOfInt C_Region_ID {
            get {
                return this.C_Region_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.C_Region_IDField, value) != true)) {
                    this.C_Region_IDField = value;
                    this.RaisePropertyChanged("C_Region_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public ModelLibrary.AcctService.ArrayOfInt To_Region_ID {
            get {
                return this.To_Region_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.To_Region_IDField, value) != true)) {
                    this.To_Region_IDField = value;
                    this.RaisePropertyChanged("To_Region_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxCategory", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TaxCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfInt IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfBoolean ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfBoolean DefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString CommodityCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ModelLibrary.AcctService.ArrayOfInt ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ModelLibrary.AcctService.ArrayOfString Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ModelLibrary.AcctService.ArrayOfString Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ModelLibrary.AcctService.ArrayOfBoolean Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveField, value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ModelLibrary.AcctService.ArrayOfBoolean Default {
            get {
                return this.DefaultField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultField, value) != true)) {
                    this.DefaultField = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ModelLibrary.AcctService.ArrayOfString CommodityCode {
            get {
                return this.CommodityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CommodityCodeField, value) != true)) {
                    this.CommodityCodeField = value;
                    this.RaisePropertyChanged("CommodityCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountingFileInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AccountingFileInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ModelLibrary.AcctService.ArrayOfString FilePathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ModelLibrary.AcctService.ArrayOfString Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ModelLibrary.AcctService.ArrayOfString Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ModelLibrary.AcctService.ArrayOfString FilePath {
            get {
                return this.FilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.FilePathField, value) != true)) {
                    this.FilePathField = value;
                    this.RaisePropertyChanged("FilePath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AcctService.AccountServiceSoap")]
    public interface AccountServiceSoap {
        
        // CODEGEN: Generating message contract since element name AccessKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrencySourceUrl", ReplyAction="*")]
        ModelLibrary.AcctService.GetCurrencySourceUrlResponse GetCurrencySourceUrl(ModelLibrary.AcctService.GetCurrencySourceUrlRequest request);
        
        // CODEGEN: Generating message contract since element name from from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConvertedCurrencyValue", ReplyAction="*")]
        ModelLibrary.AcctService.GetConvertedCurrencyValueResponse GetConvertedCurrencyValue(ModelLibrary.AcctService.GetConvertedCurrencyValueRequest request);
        
        // CODEGEN: Generating message contract since element name AccessKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentTermAccordingToCuntry", ReplyAction="*")]
        ModelLibrary.AcctService.GetPaymentTermAccordingToCuntryResponse GetPaymentTermAccordingToCuntry(ModelLibrary.AcctService.GetPaymentTermAccordingToCuntryRequest request);
        
        // CODEGEN: Generating message contract since element name AccessKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTaxRate", ReplyAction="*")]
        ModelLibrary.AcctService.GetTaxRateResponse GetTaxRate(ModelLibrary.AcctService.GetTaxRateRequest request);
        
        // CODEGEN: Generating message contract since element name AccessKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountingFileInfo", ReplyAction="*")]
        ModelLibrary.AcctService.GetAccountingFileInfoResponse GetAccountingFileInfo(ModelLibrary.AcctService.GetAccountingFileInfoRequest request);
        
        // CODEGEN: Generating message contract since element name filePath from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadAccountingFile", ReplyAction="*")]
        ModelLibrary.AcctService.DownloadAccountingFileResponse DownloadAccountingFile(ModelLibrary.AcctService.DownloadAccountingFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencySourceUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencySourceUrl", Namespace="http://tempuri.org/", Order=0)]
        public ModelLibrary.AcctService.GetCurrencySourceUrlRequestBody Body;
        
        public GetCurrencySourceUrlRequest() {
        }
        
        public GetCurrencySourceUrlRequest(ModelLibrary.AcctService.GetCurrencySourceUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrencySourceUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AccessKey;
        
        public GetCurrencySourceUrlRequestBody() {
        }
        
        public GetCurrencySourceUrlRequestBody(string AccessKey) {
            this.AccessKey = AccessKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencySourceUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencySourceUrlResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelLibrary.AcctService.GetCurrencySourceUrlResponseBody Body;
        
        public GetCurrencySourceUrlResponse() {
        }
        
        public GetCurrencySourceUrlResponse(ModelLibrary.AcctService.GetCurrencySourceUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrencySourceUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ModelLibrary.AcctService.CurrencyRateConversionUrlInfo GetCurrencySourceUrlResult;
        
        public GetCurrencySourceUrlResponseBody() {
        }
        
        public GetCurrencySourceUrlResponseBody(ModelLibrary.AcctService.CurrencyRateConversionUrlInfo GetCurrencySourceUrlResult) {
            this.GetCurrencySourceUrlResult = GetCurrencySourceUrlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConvertedCurrencyValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConvertedCurrencyValue", Namespace="http://tempuri.org/", Order=0)]
        public ModelLibrary.AcctService.GetConvertedCurrencyValueRequestBody Body;
        
        public GetConvertedCurrencyValueRequest() {
        }
        
        public GetConvertedCurrencyValueRequest(ModelLibrary.AcctService.GetConvertedCurrencyValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetConvertedCurrencyValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AccessKey;
        
        public GetConvertedCurrencyValueRequestBody() {
        }
        
        public GetConvertedCurrencyValueRequestBody(string from, string to, string url, string AccessKey) {
            this.from = from;
            this.to = to;
            this.url = url;
            this.AccessKey = AccessKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConvertedCurrencyValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConvertedCurrencyValueResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelLibrary.AcctService.GetConvertedCurrencyValueResponseBody Body;
        
        public GetConvertedCurrencyValueResponse() {
        }
        
        public GetConvertedCurrencyValueResponse(ModelLibrary.AcctService.GetConvertedCurrencyValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetConvertedCurrencyValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetConvertedCurrencyValueResult;
        
        public GetConvertedCurrencyValueResponseBody() {
        }
        
        public GetConvertedCurrencyValueResponseBody(string GetConvertedCurrencyValueResult) {
            this.GetConvertedCurrencyValueResult = GetConvertedCurrencyValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPaymentTermAccordingToCuntryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPaymentTermAccordingToCuntry", Namespace="http://tempuri.org/", Order=0)]
        public ModelLibrary.AcctService.GetPaymentTermAccordingToCuntryRequestBody Body;
        
        public GetPaymentTermAccordingToCuntryRequest() {
        }
        
        public GetPaymentTermAccordingToCuntryRequest(ModelLibrary.AcctService.GetPaymentTermAccordingToCuntryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPaymentTermAccordingToCuntryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CountryID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccessKey;
        
        public GetPaymentTermAccordingToCuntryRequestBody() {
        }
        
        public GetPaymentTermAccordingToCuntryRequestBody(int CountryID, string AccessKey) {
            this.CountryID = CountryID;
            this.AccessKey = AccessKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPaymentTermAccordingToCuntryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPaymentTermAccordingToCuntryResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelLibrary.AcctService.GetPaymentTermAccordingToCuntryResponseBody Body;
        
        public GetPaymentTermAccordingToCuntryResponse() {
        }
        
        public GetPaymentTermAccordingToCuntryResponse(ModelLibrary.AcctService.GetPaymentTermAccordingToCuntryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPaymentTermAccordingToCuntryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ModelLibrary.AcctService.PaymentTerm GetPaymentTermAccordingToCuntryResult;
        
        public GetPaymentTermAccordingToCuntryResponseBody() {
        }
        
        public GetPaymentTermAccordingToCuntryResponseBody(ModelLibrary.AcctService.PaymentTerm GetPaymentTermAccordingToCuntryResult) {
            this.GetPaymentTermAccordingToCuntryResult = GetPaymentTermAccordingToCuntryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTaxRateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTaxRate", Namespace="http://tempuri.org/", Order=0)]
        public ModelLibrary.AcctService.GetTaxRateRequestBody Body;
        
        public GetTaxRateRequest() {
        }
        
        public GetTaxRateRequest(ModelLibrary.AcctService.GetTaxRateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTaxRateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CountryID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccessKey;
        
        public GetTaxRateRequestBody() {
        }
        
        public GetTaxRateRequestBody(int CountryID, string AccessKey) {
            this.CountryID = CountryID;
            this.AccessKey = AccessKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTaxRateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTaxRateResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelLibrary.AcctService.GetTaxRateResponseBody Body;
        
        public GetTaxRateResponse() {
        }
        
        public GetTaxRateResponse(ModelLibrary.AcctService.GetTaxRateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTaxRateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ModelLibrary.AcctService.TaxMgmt GetTaxRateResult;
        
        public GetTaxRateResponseBody() {
        }
        
        public GetTaxRateResponseBody(ModelLibrary.AcctService.TaxMgmt GetTaxRateResult) {
            this.GetTaxRateResult = GetTaxRateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountingFileInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountingFileInfo", Namespace="http://tempuri.org/", Order=0)]
        public ModelLibrary.AcctService.GetAccountingFileInfoRequestBody Body;
        
        public GetAccountingFileInfoRequest() {
        }
        
        public GetAccountingFileInfoRequest(ModelLibrary.AcctService.GetAccountingFileInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountingFileInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AccessKey;
        
        public GetAccountingFileInfoRequestBody() {
        }
        
        public GetAccountingFileInfoRequestBody(string AccessKey) {
            this.AccessKey = AccessKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountingFileInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountingFileInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelLibrary.AcctService.GetAccountingFileInfoResponseBody Body;
        
        public GetAccountingFileInfoResponse() {
        }
        
        public GetAccountingFileInfoResponse(ModelLibrary.AcctService.GetAccountingFileInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountingFileInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ModelLibrary.AcctService.AccountingFileInfo GetAccountingFileInfoResult;
        
        public GetAccountingFileInfoResponseBody() {
        }
        
        public GetAccountingFileInfoResponseBody(ModelLibrary.AcctService.AccountingFileInfo GetAccountingFileInfoResult) {
            this.GetAccountingFileInfoResult = GetAccountingFileInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadAccountingFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadAccountingFile", Namespace="http://tempuri.org/", Order=0)]
        public ModelLibrary.AcctService.DownloadAccountingFileRequestBody Body;
        
        public DownloadAccountingFileRequest() {
        }
        
        public DownloadAccountingFileRequest(ModelLibrary.AcctService.DownloadAccountingFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownloadAccountingFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccessKey;
        
        public DownloadAccountingFileRequestBody() {
        }
        
        public DownloadAccountingFileRequestBody(string filePath, string AccessKey) {
            this.filePath = filePath;
            this.AccessKey = AccessKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadAccountingFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadAccountingFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelLibrary.AcctService.DownloadAccountingFileResponseBody Body;
        
        public DownloadAccountingFileResponse() {
        }
        
        public DownloadAccountingFileResponse(ModelLibrary.AcctService.DownloadAccountingFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownloadAccountingFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DownloadAccountingFileResult;
        
        public DownloadAccountingFileResponseBody() {
        }
        
        public DownloadAccountingFileResponseBody(byte[] DownloadAccountingFileResult) {
            this.DownloadAccountingFileResult = DownloadAccountingFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountServiceSoapChannel : ModelLibrary.AcctService.AccountServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceSoapClient : System.ServiceModel.ClientBase<ModelLibrary.AcctService.AccountServiceSoap>, ModelLibrary.AcctService.AccountServiceSoap {
        
        public AccountServiceSoapClient() {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelLibrary.AcctService.GetCurrencySourceUrlResponse ModelLibrary.AcctService.AccountServiceSoap.GetCurrencySourceUrl(ModelLibrary.AcctService.GetCurrencySourceUrlRequest request) {
            return base.Channel.GetCurrencySourceUrl(request);
        }
        
        public ModelLibrary.AcctService.CurrencyRateConversionUrlInfo GetCurrencySourceUrl(string AccessKey) {
            ModelLibrary.AcctService.GetCurrencySourceUrlRequest inValue = new ModelLibrary.AcctService.GetCurrencySourceUrlRequest();
            inValue.Body = new ModelLibrary.AcctService.GetCurrencySourceUrlRequestBody();
            inValue.Body.AccessKey = AccessKey;
            ModelLibrary.AcctService.GetCurrencySourceUrlResponse retVal = ((ModelLibrary.AcctService.AccountServiceSoap)(this)).GetCurrencySourceUrl(inValue);
            return retVal.Body.GetCurrencySourceUrlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelLibrary.AcctService.GetConvertedCurrencyValueResponse ModelLibrary.AcctService.AccountServiceSoap.GetConvertedCurrencyValue(ModelLibrary.AcctService.GetConvertedCurrencyValueRequest request) {
            return base.Channel.GetConvertedCurrencyValue(request);
        }
        
        public string GetConvertedCurrencyValue(string from, string to, string url, string AccessKey) {
            ModelLibrary.AcctService.GetConvertedCurrencyValueRequest inValue = new ModelLibrary.AcctService.GetConvertedCurrencyValueRequest();
            inValue.Body = new ModelLibrary.AcctService.GetConvertedCurrencyValueRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.url = url;
            inValue.Body.AccessKey = AccessKey;
            ModelLibrary.AcctService.GetConvertedCurrencyValueResponse retVal = ((ModelLibrary.AcctService.AccountServiceSoap)(this)).GetConvertedCurrencyValue(inValue);
            return retVal.Body.GetConvertedCurrencyValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelLibrary.AcctService.GetPaymentTermAccordingToCuntryResponse ModelLibrary.AcctService.AccountServiceSoap.GetPaymentTermAccordingToCuntry(ModelLibrary.AcctService.GetPaymentTermAccordingToCuntryRequest request) {
            return base.Channel.GetPaymentTermAccordingToCuntry(request);
        }
        
        public ModelLibrary.AcctService.PaymentTerm GetPaymentTermAccordingToCuntry(int CountryID, string AccessKey) {
            ModelLibrary.AcctService.GetPaymentTermAccordingToCuntryRequest inValue = new ModelLibrary.AcctService.GetPaymentTermAccordingToCuntryRequest();
            inValue.Body = new ModelLibrary.AcctService.GetPaymentTermAccordingToCuntryRequestBody();
            inValue.Body.CountryID = CountryID;
            inValue.Body.AccessKey = AccessKey;
            ModelLibrary.AcctService.GetPaymentTermAccordingToCuntryResponse retVal = ((ModelLibrary.AcctService.AccountServiceSoap)(this)).GetPaymentTermAccordingToCuntry(inValue);
            return retVal.Body.GetPaymentTermAccordingToCuntryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelLibrary.AcctService.GetTaxRateResponse ModelLibrary.AcctService.AccountServiceSoap.GetTaxRate(ModelLibrary.AcctService.GetTaxRateRequest request) {
            return base.Channel.GetTaxRate(request);
        }
        
        public ModelLibrary.AcctService.TaxMgmt GetTaxRate(int CountryID, string AccessKey) {
            ModelLibrary.AcctService.GetTaxRateRequest inValue = new ModelLibrary.AcctService.GetTaxRateRequest();
            inValue.Body = new ModelLibrary.AcctService.GetTaxRateRequestBody();
            inValue.Body.CountryID = CountryID;
            inValue.Body.AccessKey = AccessKey;
            ModelLibrary.AcctService.GetTaxRateResponse retVal = ((ModelLibrary.AcctService.AccountServiceSoap)(this)).GetTaxRate(inValue);
            return retVal.Body.GetTaxRateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelLibrary.AcctService.GetAccountingFileInfoResponse ModelLibrary.AcctService.AccountServiceSoap.GetAccountingFileInfo(ModelLibrary.AcctService.GetAccountingFileInfoRequest request) {
            return base.Channel.GetAccountingFileInfo(request);
        }
        
        public ModelLibrary.AcctService.AccountingFileInfo GetAccountingFileInfo(string AccessKey) {
            ModelLibrary.AcctService.GetAccountingFileInfoRequest inValue = new ModelLibrary.AcctService.GetAccountingFileInfoRequest();
            inValue.Body = new ModelLibrary.AcctService.GetAccountingFileInfoRequestBody();
            inValue.Body.AccessKey = AccessKey;
            ModelLibrary.AcctService.GetAccountingFileInfoResponse retVal = ((ModelLibrary.AcctService.AccountServiceSoap)(this)).GetAccountingFileInfo(inValue);
            return retVal.Body.GetAccountingFileInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelLibrary.AcctService.DownloadAccountingFileResponse ModelLibrary.AcctService.AccountServiceSoap.DownloadAccountingFile(ModelLibrary.AcctService.DownloadAccountingFileRequest request) {
            return base.Channel.DownloadAccountingFile(request);
        }
        
        public byte[] DownloadAccountingFile(string filePath, string AccessKey) {
            ModelLibrary.AcctService.DownloadAccountingFileRequest inValue = new ModelLibrary.AcctService.DownloadAccountingFileRequest();
            inValue.Body = new ModelLibrary.AcctService.DownloadAccountingFileRequestBody();
            inValue.Body.filePath = filePath;
            inValue.Body.AccessKey = AccessKey;
            ModelLibrary.AcctService.DownloadAccountingFileResponse retVal = ((ModelLibrary.AcctService.AccountServiceSoap)(this)).DownloadAccountingFile(inValue);
            return retVal.Body.DownloadAccountingFileResult;
        }
    }
}
