/*
 * Globalize Culture ru-RU
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "ru-RU", "default", {
	name: "ru-RU",
	englishName: "Russian (Russia)",
	nativeName: "русский (Россия)",
	language: "ru",
	numberFormat: {
		",": " ",
		".": ",",
		negativeInfinity: "-бесконечность",
		positiveInfinity: "бесконечность",
		percent: {
			pattern: ["-n%","n%"],
			",": " ",
			".": ","
		},
		currency: {
			pattern: ["-n$","n$"],
			",": " ",
			".": ",",
			symbol: "р."
		}
	},
	calendars: {
		standard: {
			"/": ".",
			firstDay: 1,
			days: {
				names: ["воскресенье","понедельник","вторник","среда","четверг","пятница","суббота"],
				namesAbbr: ["Вс","Пн","Вт","Ср","Чт","Пт","Сб"],
				namesShort: ["Вс","Пн","Вт","Ср","Чт","Пт","Сб"]
			},
			months: {
				names: ["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь",""],
				namesAbbr: ["янв","фев","мар","апр","май","июн","июл","авг","сен","окт","ноя","дек",""]
			},
			monthsGenitive: {
				names: ["января","февраля","марта","апреля","мая","июня","июля","августа","сентября","октября","ноября","декабря",""],
				namesAbbr: ["янв","фев","мар","апр","май","июн","июл","авг","сен","окт","ноя","дек",""]
			},
			AM: null,
			PM: null,
			patterns: {
				d: "dd.MM.yyyy",
				D: "d MMMM yyyy 'г.'",
				t: "H:mm",
				T: "H:mm:ss",
				f: "d MMMM yyyy 'г.' H:mm",
				F: "d MMMM yyyy 'г.' H:mm:ss",
				Y: "MMMM yyyy"
			}
		}
	},
	messages:
        {
            "Connection": "\u0421\u043e\u0435\u0434\u0438\u043d\u0435\u043d\u0438\u0435",
    "Defaults": "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u044f \u043f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e",
    "Login": "\u0412\u0445\u043e\u0434",
    "File": "\u0424\u0430\u0439\u043b",
    "Exit": "\u0412\u044b\u0445\u043e\u0434",
    "Help": "\u041f\u043e\u043c\u043e\u0449\u044c",
    "About": "\u041e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435",
    "Host": "\u0425\u043e\u0441\u0442",
    "Database": "\u0411\u0430\u0437\u0430 \u0434\u0430\u043d\u043d\u044b\u0445",
    "User": "\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c",
    "EnterUser": "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f",
    "Password": "\u041f\u0430\u0440\u043e\u043b\u044c",
    "EnterPassword": "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043f\u0430\u0440\u043e\u043b\u044c",
    "Language": "\u042f\u0437\u044b\u043a",
    "SelectLanguage": "\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0432\u0430\u0448 \u044f\u0437\u044b\u043a",
    "Role": "\u0420\u043e\u043b\u044c",
    "Client": "\u041a\u043b\u0438\u0435\u043d\u0442",
    "Organization": "\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f",
    "Date": "\u0414\u0430\u0442\u0430",
    "Warehouse": "\u0421\u043a\u043b\u0430\u0434",
    "Printer": "\u041f\u0440\u0438\u043d\u0442\u0435\u0440",
    "Connected": "\u0421\u043e\u0435\u0434\u0438\u043d\u0435\u043d\u043e",
    "NotConnected": "\u041d\u0435 \u0441\u043e\u0435\u0434\u0438\u043d\u0435\u043d\u043e",
    "DatabaseNotFound": "\u0411\u0430\u0437\u0430 \u0434\u0430\u043d\u043d\u044b\u0445 \u043d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d\u0430",
    "UserPwdError": "\u041d\u0435 \u0432\u0435\u0440\u043d\u044b\u0439 \u043f\u0430\u0440\u043e\u043b\u044c",
    "RoleNotFound": "\u041d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d\u0430 \u0440\u043e\u043b\u044c",
    "Authorized": "\u0410\u0432\u0442\u043e\u0440\u0438\u0437\u043e\u0432\u0430\u043d",
    "Ok": "\u0414\u0430",
    "Cancel": "\u041e\u0442\u043c\u0435\u043d\u0430",
    "VersionConflict": "\u041a\u043e\u043d\u0444\u043b\u0438\u043a\u0442 \u0432\u0435\u0440\u0441\u0438\u0439:",
    "VersionInfo": "\u0421\u0435\u0440\u0432\u0435\u0440 <> \u041a\u043b\u0438\u0435\u043d\u0442",
    "PleaseUpgrade": "\u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430 \u0437\u0430\u043f\u0443\u0441\u0442\u0438\u0442\u0435 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0443 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f",

    //New Resource

    "Back": "назад",
    "SelectRole": "Выберите роль",
    "SelectOrg": "Выберите организацию",
    "SelectClient": "Выбор клиента",
    "SelectWarehouse": "Выберите склад",
    "VerifyUserLanguage": "Проверка пользователя и языка",
    "LoadingPreference": "загрузка предпочтения",
    "Completed": "завершенный",
    "RememberMe": "Запомнить Меня",
        }
});

}( this ));
