/*
 * Globalize Culture pt-BR
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "pt-BR", "default", {
	name: "pt-BR",
	englishName: "Portuguese (Brazil)",
	nativeName: "Português (Brasil)",
	language: "pt",
	numberFormat: {
		",": ".",
		".": ",",
		"NaN": "NaN (Não é um número)",
		negativeInfinity: "-Infinito",
		positiveInfinity: "+Infinito",
		percent: {
			pattern: ["-n%","n%"],
			",": ".",
			".": ","
		},
		currency: {
			pattern: ["-$ n","$ n"],
			",": ".",
			".": ",",
			symbol: "R$"
		}
	},
	calendars: {
		standard: {
			days: {
				names: ["domingo","segunda-feira","terça-feira","quarta-feira","quinta-feira","sexta-feira","sábado"],
				namesAbbr: ["dom","seg","ter","qua","qui","sex","sáb"],
				namesShort: ["D","S","T","Q","Q","S","S"]
			},
			months: {
				names: ["janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro",""],
				namesAbbr: ["jan","fev","mar","abr","mai","jun","jul","ago","set","out","nov","dez",""]
			},
			AM: null,
			PM: null,
			eras: [{"name":"d.C.","start":null,"offset":0}],
			patterns: {
				d: "dd/MM/yyyy",
				D: "dddd, d' de 'MMMM' de 'yyyy",
				t: "HH:mm",
				T: "HH:mm:ss",
				f: "dddd, d' de 'MMMM' de 'yyyy HH:mm",
				F: "dddd, d' de 'MMMM' de 'yyyy HH:mm:ss",
				M: "dd' de 'MMMM",
				Y: "MMMM' de 'yyyy"
			}
		}
	},
	messages: {
	    "Connection": "Conexão",
    "Defaults": "Padrões",
    "Login": "Conecte-Se",
    "File": "Arquivo",
    "Exit": "Sair",
    "Help": "Ajuda",
    "About": "Sobre",
    "Host": "Servidor",
    "Database": "Banco de Dados",
    "User": "ID Usuário",
    "EnterUser": "Entre com o ID Usuário da Aplicação",
    "Password": "Senha",
    "EnterPassword": "Entre com a Senha da Aplicação",
    "Language": "Idioma",
    "SelectLanguage": "Selecione o idioma",
    "Role": "Regra",
    "Client": "Cliente",
    "Organization": "Organização",
    "Date": "Data",
    "Warehouse": "Depósito",
    "Printer": "Impressora",
    "Connected": "Conectado",
    "NotConnected": "Não conectado",
    "DatabaseNotFound": "Banco de Dados não encontrado",
    "UserPwdError": "Usuário/Senha inválidos",
    "RoleNotFound": "Regra não encontrada/incorreta",
    "Authorized": "Autorizado",
    "Ok": "Ok",
    "Cancel": "Cancelar",
    "VersionConflict": "Conflito de Versões:",
    "VersionInfo": "Servidor <> Cliente",
    "PleaseUpgrade": "Favor executar o programa de atualização",

    //New Resource

    "Back": "de volta",
    "SelectRole": "Selecione Papel",
    "SelectOrg": "Selecione Organização",
    "SelectClient": "Selecione Cliente",
    "SelectWarehouse": "Selecione Armazém",
    "VerifyUserLanguage": "Verificando usuário e linguagem",
    "LoadingPreference": "Carregando Preferências",
    "Completed": "concluído",
        "RememberMe": "Lembre De Mim",
        "FillMandatoryFields": "Preencher campos obrigatórios",
        "BothPwdNotMatch": "As duas senhas devem corresponder.",
        "mustMatchCriteria": "O tamanho mínimo da senha é 5. A senha deve ter pelo menos 1 caractere maiúsculo, 1 minúsculo, um caractere especial (@ $!% *? &) E um dígito. A senha deve começar com o caractere.",
        "NotLoginUser": "O usuário não pode fazer login no sistema",
        "MaxFailedLoginAttempts": "A conta do usuário está bloqueada. O número máximo de tentativas com falha no login excede o limite definido. Entre em contato com o administrador.",
        "UserNotFound": "Nome de usuário incorreto.",
        "RoleNotDefined": "Nenhuma função definida para este usuário",
        "oldNewSamePwd": "senha antiga e nova senha devem ser diferentes.",
        "NewPassword": "Nova senha",
        "NewCPassword": "Confirme a nova senha",
        "EnterOTP": "Digite OTP",
        "WrongOTP": "OTP incorreto digitado",
        "ScanQRCode": "Digitalize o código com o Google Authenticator",
        "EnterVerCode": "Digite o OTP gerado pelo seu aplicativo móvel"
	}
});

}( this ));
