/*
 * Globalize Culture pl-PL
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

    var Globalize;

    if ( typeof require !== "undefined" &&
        typeof exports !== "undefined" &&
        typeof module !== "undefined" ) {
        // Assume CommonJS
        Globalize = require( "globalize" );
    } else {
        // Global variable
        Globalize = window.Globalize;
    }

    Globalize.addCultureInfo( "pl-PL", "default", {
        name: "pl-PL",
        englishName: "Polish (Poland)",
        nativeName: "polski (Polska)",
        language: "pl",
        numberFormat: {
            ",": " ",
            ".": ",",
            "NaN": "nie jest liczbą",
            negativeInfinity: "-nieskończoność",
            positiveInfinity: "+nieskończoność",
            percent: {
                pattern: ["-n%","n%"],
                ",": " ",
                ".": ","
            },
            currency: {
                pattern: ["-n $","n $"],
                ",": " ",
                ".": ",",
                symbol: "zł"
            }
        },
        calendars: {
            standard: {
                "/": "-",
                firstDay: 1,
                days: {
                    names: ["niedziela","poniedziałek","wtorek","środa","czwartek","piątek","sobota"],
                    namesAbbr: ["niedz.","pon.","wt.","śr.","czw.","pt.","sob."],
                    namesShort: ["N","Pn","Wt","Śr","Cz","Pt","So"]
                },
                months: {
                    names: ["styczeń","luty","marzec","kwiecień","maj","czerwiec","lipiec","sierpień","wrzesień","październik","listopad","grudzień",""],
                    namesAbbr: ["sty","lut","mar","kwi","maj","cze","lip","sie","wrz","paź","lis","gru",""]
                },
                monthsGenitive: {
                    names: ["stycznia","lutego","marca","kwietnia","maja","czerwca","lipca","sierpnia","września","października","listopada","grudnia",""],
                    namesAbbr: ["sty","lut","mar","kwi","maj","cze","lip","sie","wrz","paź","lis","gru",""]
                },
                AM: null,
                PM: null,
                patterns: {
                    d: "yyyy-MM-dd",
                    D: "d MMMM yyyy",
                    t: "HH:mm",
                    T: "HH:mm:ss",
                    f: "d MMMM yyyy HH:mm",
                    F: "d MMMM yyyy HH:mm:ss",
                    M: "d MMMM",
                    Y: "MMMM yyyy"
                }
            }
        },
        messages:{
            "Connection": "Po\u0142\u0105czenie",
    "Defaults": "Domy\u015blne",
    "Login": "Logowanie",
    "File": "Plik",
    "Exit": "Zako\u0144cz",
    "Help": "Pomoc",
    "About": "O aplikacji",
    "Host": "Host",
    "Database": "Baza danych",
    "User": "U\u017cytkownik",
    "EnterUser": "Wprowad\u017a Identyfikator U\u017cytkownika Aplikacji",
    "Password": "Has\u0142o",
    "EnterPassword": "Wprowad\u017a Has\u0142o Aplikacji",
    "Language": "J\u0119zyk",
    "SelectLanguage": "Wybierz j\u0119zyk",
    "Role": "Funkcja",
    "Client": "Klient",
    "Organization": "Organizacja",
    "Date": "Data",
    "Warehouse": "Magazyn",
    "Printer": "Drukarka",
    "Connected": "Po\u0142\u0105czony",
    "NotConnected": "Nie Po\u0142\u0105czony",
    "DatabaseNotFound": "Nie znaleziono bazy danych",
    "UserPwdError": "Has\u0142o nie odpowiada U\u017cytkownikowi",
    "RoleNotFound": "Nie znaleziono zasady",
    "Authorized": "Autoryzowany",
    "Ok": "Ok",
    "Cancel": "Anuluj",
    "VersionConflict": "Konflikt wersji:",
    "VersionInfo": "Serwer <> Klienta",
    "PleaseUpgrade": "Uruchom now\u0105 wersj\u0119 programu !",


    //New Resource

    "Back": "z powrotem",
    "SelectRole": "Wybierz rolę",
    "SelectOrg": "Wybierz Organizację",
    "SelectClient": "Wybierz klienta",
    "SelectWarehouse": "Wybierz Warehouse",
    "VerifyUserLanguage": "Weryfikacja użytkownika i język",
    "LoadingPreference": "Ładowanie Preference",
    "Completed": "zakończony",
            "RememberMe": "Zapamiętaj mnie",
            "FillMandatoryFields": "Wypełnij pola obowiązkowe",
            "BothPwdNotMatch": "Oba hasła muszą się zgadzać.",
            "mustMatchCriteria": "Minimalna długość hasła to 5. Hasło musi zawierać co najmniej 1 wielką literę, 1 małą literę, jeden znak specjalny (@ $!% *? &) I jedną cyfrę. Hasło musi zaczynać się od znaku.",
            "NotLoginUser": "Użytkownik nie może zalogować się do systemu",
            "MaxFailedLoginAttempts": "Konto użytkownika jest zablokowane. Maksymalna liczba nieudanych prób logowania przekracza zdefiniowany limit. Skontaktuj się z administratorem.",
            "UserNotFound": "Nazwa użytkownika jest niepoprawna.",
            "RoleNotDefined": "Nie zdefiniowano roli dla tego użytkownika",
            "oldNewSamePwd": "stare hasło i nowe hasło muszą być inne.",
            "NewPassword": "nowe hasło",
            "NewCPassword": "Potwierdź nowe hasło",
            "EnterOTP": "Wpisz OTP",
            "WrongOTP": "Wprowadzono nieprawidłowy kod OTP",
            "ScanQRCode": "Zeskanuj kod za pomocą Google Authenticator",
            "EnterVerCode": "Wpisz OTP wygenerowane przez aplikację mobilną"
}
});

}( this ));
