/*
 * Globalize Culture es-UY
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "es-UY", "default", {
	name: "es-UY",
	englishName: "Spanish (Uruguay)",
	nativeName: "Español (Uruguay)",
	language: "es",
	numberFormat: {
		",": ".",
		".": ",",
		"NaN": "NeuN",
		negativeInfinity: "-Infinito",
		positiveInfinity: "Infinito",
		percent: {
			",": ".",
			".": ","
		},
		currency: {
			pattern: ["($ n)","$ n"],
			",": ".",
			".": ",",
			symbol: "$U"
		}
	},
	calendars: {
		standard: {
			firstDay: 1,
			days: {
				names: ["domingo","lunes","martes","miércoles","jueves","viernes","sábado"],
				namesAbbr: ["dom","lun","mar","mié","jue","vie","sáb"],
				namesShort: ["do","lu","ma","mi","ju","vi","sá"]
			},
			months: {
				names: ["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre",""],
				namesAbbr: ["ene","feb","mar","abr","may","jun","jul","ago","sep","oct","nov","dic",""]
			},
			AM: ["a.m.","a.m.","A.M."],
			PM: ["p.m.","p.m.","P.M."],
			eras: [{"name":"d.C.","start":null,"offset":0}],
			patterns: {
				d: "dd/MM/yyyy",
				D: "dddd, dd' de 'MMMM' de 'yyyy",
				t: "hh:mm tt",
				T: "hh:mm:ss tt",
				f: "dddd, dd' de 'MMMM' de 'yyyy hh:mm tt",
				F: "dddd, dd' de 'MMMM' de 'yyyy hh:mm:ss tt",
				M: "dd MMMM",
				Y: "MMMM' de 'yyyy"
			}
		}
	},
	messages: {
	    "Connection": "Conección",
	    "Defaults": "Predeterminados",
	    "Login": "Acceso",
	    "File": "Archivo",
	    "Exit": "Salir",
	    "Help": "Ayuda",
	    "About": "Acerca de",
	    "Host": "Huesped",
	    "Database": "Base de Datos",
	    "User": "Usuario",
	    "EnterUser": "Introduzca ID de usuario de aplicaciones",
	    "Password": "Contraseña",
	    "EnterPassword": "Introduzca Aplicación Contraseña",
	    "Language": "Idioma",
	    "SelectLanguage": "Seleccione su idioma",
	    "Role": "Rol",
	    "Client": "Cliente",
	    "Organization": "Oganización",
	    "Date": "Fecha",
	    "Warehouse": "Almacén",
	    "Printer": "Impresora",
	    "Connected": "Conectado",
	    "NotConnected": "No conectado",
	    "DatabaseNotFound": "Base de datos que no se encuentran",
	    "UserPwdError": "Usuario no coincide con la contraseña",
	    "RoleNotFound": "Papel no encontrado / completa",
	    "Authorized": "Autorizado",
	    "Ok": "Aceptar",
	    "Cancel": "Cancelar",
	    "VersionConflict": "conflicto de versiones",
	    "VersionInfo": "Servidor <> Cliente",
	    "PleaseUpgrade": "Por favor, descargue la nueva versión del servidor",
	    //New Resource
	    "Back": "Atrás",
	    "SelectRole": "Seleccione Rol",
	    "SelectOrg": "Seleccione Organización",
	    "SelectClient": "Seleccione Cliente",
	    "SelectWarehouse": "Seleccione Almacen",
	    "VerifyUserLanguage": "Verificando usuario y el idioma",
	    "LoadingPreference": "Cargando Configuaciones",
	    "Completed": "Completado",
	    "DefaultLoginLanguage": "es_UY",
	    "RememberMe": "Recordarme",
        "FillMandatoryFields": "Complete Campos Requeridos",
        "BothPwdNotMatch": "Ambas contraseñas deben coincidir.",
        "mustMatchCriteria": "La longitud mínima para la contraseña es 5. La contraseña debe tener al menos 1 carácter en mayúscula, 1 carácter en minúscula, un carácter especial (@ $!% *? &) Y un dígito. La contraseña debe comenzar con el carácter.",
        "NotLoginUser": "El usuario no puede iniciar sesión en el sistema",
        "MaxFailedLoginAttempts": "La cuenta de usuario está bloqueada. Los intentos de inicio de sesión fallidos máximos exceden el límite definido. Por favor, póngase en contacto con el administrador.",
        "UserNotFound": "El nombre de usuario es incorrecto.",
        "RoleNotDefined": "Ningún rol definido para este usuario",
        "oldNewSamePwd": "la contraseña anterior y la nueva deben ser diferentes.",
        "NewPassword": "Nueva contraseña",
        "NewCPassword": "Confirmar nueva contraseña",
        "EnterOTP": "Ingrese OTP",
        "WrongOTP": "OTP incorrecto ingresado",
        "ScanQRCode": "Escanee el código con Google Authenticator",
        "EnterVerCode": "Ingrese la OTP generada por su aplicación móvil",
	}
});

}( this ));
