/*
 * Globalize Culture da-DK
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "da-DK", "default", {
	name: "da-DK",
	englishName: "Danish (Denmark)",
	nativeName: "dansk (Danmark)",
	language: "da",
	numberFormat: {
		",": ".",
		".": ",",
		negativeInfinity: "-INF",
		positiveInfinity: "INF",
		percent: {
			",": ".",
			".": ","
		},
		currency: {
			pattern: ["$ -n","$ n"],
			",": ".",
			".": ",",
			symbol: "kr."
		}
	},
	calendars: {
		standard: {
			"/": "-",
			firstDay: 1,
			days: {
				names: ["søndag","mandag","tirsdag","onsdag","torsdag","fredag","lørdag"],
				namesAbbr: ["sø","ma","ti","on","to","fr","lø"],
				namesShort: ["sø","ma","ti","on","to","fr","lø"]
			},
			months: {
				names: ["januar","februar","marts","april","maj","juni","juli","august","september","oktober","november","december",""],
				namesAbbr: ["jan","feb","mar","apr","maj","jun","jul","aug","sep","okt","nov","dec",""]
			},
			AM: null,
			PM: null,
			patterns: {
				d: "dd-MM-yyyy",
				D: "d. MMMM yyyy",
				t: "HH:mm",
				T: "HH:mm:ss",
				f: "d. MMMM yyyy HH:mm",
				F: "d. MMMM yyyy HH:mm:ss",
				M: "d. MMMM",
				Y: "MMMM yyyy"
			}
		}
	},
	messages: {
	    "Connection": "Forbindelse",
    "Defaults": "Basis",
    "Login": "Log pÃ¥",
    "File": "Fil",
    "Exit": "Afslut",
    "Help": "HjÃ¦lp",
    "About": "Om",
    "Host": "VÃ¦rt",
    "Database": "Database",
    "User": "Bruger-ID",
    "EnterUser": "Angiv bruger-ID til program",
    "Password": "Adgangskode",
    "EnterPassword": "Angiv adgangskode til program",
    "Language": "Sprog",
    "SelectLanguage": "VÃ¦lg sprog",
    "Role": "Rolle",
    "Client": "Firma",
    "Organization": "Organisation",
    "Date": "Dato",
    "Warehouse": "Lager",
    "Printer": "Printer",
    "Connected": "Forbindelse OK",
    "NotConnected": "Ingen forbindelse",
    "DatabaseNotFound": "Database blev ikke fundet",
    "UserPwdError": "Forkert bruger til adgangskode",
    "RoleNotFound": "Rolle blev ikke fundet/afsluttet",
    "Authorized": "Tilladelse OK",
    "Ok": "OK",
    "Cancel": "AnnullÃ©r",
    "VersionConflict": "Konflikt:",
    "VersionInfo": "Server <> Klient",
    "PleaseUpgrade": "KÃ¸r opdateringsprogram",

    //New Resource

    "Back": "Tilbage",
    "SelectRole": "Vælg rolle",
    "SelectOrg": "Vælg organisation",
    "SelectClient": "Vælg klient",
    "SelectWarehouse": "Vælg Warehouse",
    "VerifyUserLanguage": "Kontrol bruger og sprog",
    "LoadingPreference": "Ilægning Preference",
    "Completed": "Afsluttet",
        "RememberMe": "Husk mig",
        "FillMandatoryFields": "Udfyld obligatoriske felter",
        "BothPwdNotMatch": "Begge adgangskoder skal matche.",
        "mustMatchCriteria": "Minimumslængde for adgangskode er 5. Adgangskode skal have mindst 1 store bogstaver, 1 små bogstaver, et specialtegn (@ $!% *? &) Og et ciffer. Adgangskode skal starte med tegn.",
        "NotLoginUser": "Brugeren kan ikke logge ind på systemet",
        "MaxFailedLoginAttempts": "Brugerkonti er låst. Maksimum mislykkede loginforsøg overstiger den definerede grænse. Kontakt venligst til administrator.",
        "UserNotFound": "Brugernavn er forkert.",
        "RoleNotDefined": "Ingen rolle defineret for denne bruger",
        "oldNewSamePwd": "den gamle adgangskode og den nye adgangskode skal være forskellige.",
        "NewPassword": "nyt kodeord",
        "NewCPassword": "Bekræft ny adgangskode",
        "EnterOTP": "Indtast OTP",
        "WrongOTP": "Forkert OTP indtastet",
        "ScanQRCode": "Scan koden med Google Authenticator",
        "EnterVerCode": "Indtast OTP genereret af din mobilapplikation",
	}
});

}( this ));
