/*
 * Globalize Culture ro-RO
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "ro-RO", "default", {
	name: "ro-RO",
	englishName: "Romanian (Romania)",
	nativeName: "română (România)",
	language: "ro",
	numberFormat: {
		",": ".",
		".": ",",
		percent: {
			pattern: ["-n%","n%"],
			",": ".",
			".": ","
		},
		currency: {
			pattern: ["-n $","n $"],
			",": ".",
			".": ",",
			symbol: "lei"
		}
	},
	calendars: {
		standard: {
			"/": ".",
			firstDay: 1,
			days: {
				names: ["duminică","luni","marţi","miercuri","joi","vineri","sâmbătă"],
				namesAbbr: ["D","L","Ma","Mi","J","V","S"],
				namesShort: ["D","L","Ma","Mi","J","V","S"]
			},
			months: {
				names: ["ianuarie","februarie","martie","aprilie","mai","iunie","iulie","august","septembrie","octombrie","noiembrie","decembrie",""],
				namesAbbr: ["ian.","feb.","mar.","apr.","mai.","iun.","iul.","aug.","sep.","oct.","nov.","dec.",""]
			},
			AM: null,
			PM: null,
			patterns: {
				d: "dd.MM.yyyy",
				D: "d MMMM yyyy",
				t: "HH:mm",
				T: "HH:mm:ss",
				f: "d MMMM yyyy HH:mm",
				F: "d MMMM yyyy HH:mm:ss",
				M: "d MMMM",
				Y: "MMMM yyyy"
			}
		}
	},
	messages: {
	   "Connection": "Conexiune",
   "Defaults": "Valori implicite",
   "Login": "Autentificare",
   "File": "Aplica\u0163ie",
   "Exit": "Ie\u015fire",
   "Help": "Ajutor",
   "About": "Despre...",
   "Host": "Server",
   "Database": "Baz\u0103 de date",
   "User": "Utilizator",
   "EnterUser": "Introduce\u0163i identificatorul utilizatorului",
   "Password": "Parol\u0103",
   "EnterPassword": "Introduce\u0163i parola",
   "Language": "Limb\u0103",
   "SelectLanguage": "Alege\u0163i limba dumneavoastr\u0103",
   "Role": "Rol",
   "Client": "Titular",
   "Organization": "Organiza\u0163ie",
   "Date": "Dat\u0103",
   "Warehouse": "Depozit",
   "Printer": "Imprimant\u0103",
   "Connected": "Conectat",
   "NotConnected": "Neconectat",
   "DatabaseNotFound": "Baza de date nu a fost g\u0103sit\u0103",
   "UserPwdError": "Parola nu se potrive\u015fte cu utilizatorul",
   "RoleNotFound": "Rolul nu a fost g\u0103sit sau este incomplet",
   "Authorized": "Autorizat",
   "Ok": "OK",
   "Cancel": "Anulare",
   "VersionConflict": "Conflict de versiune:",
   "VersionInfo": "server <> client",
   "PleaseUpgrade": "Rula\u0163i programul de actualizare",

    //New Resource

   "Back": "înapoi",
   "SelectRole": "Selectați Rolul",
   "SelectOrg": "Selectați Organizația",
   "SelectClient": "Selectați client",
   "SelectWarehouse": "Selectați depozit",
   "VerifyUserLanguage": "Verificarea de utilizator și limba",
   "LoadingPreference": "încărcarea Preferințe",
   "Completed": "terminat",
   "RememberMe": "Ține-Mă Minte",
	}
});

}( this ));
