/*
 * Globalize Culture id-ID
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "id-ID", "default", {
	name: "id-ID",
	englishName: "Indonesian (Indonesia)",
	nativeName: "Bahasa Indonesia (Indonesia)",
	language: "id",
	numberFormat: {
		",": ".",
		".": ",",
		percent: {
			",": ".",
			".": ","
		},
		currency: {
			decimals: 0,
			",": ".",
			".": ",",
			symbol: "Rp"
		}
	},
	calendars: {
		standard: {
			firstDay: 1,
			days: {
				names: ["Minggu","Senin","Selasa","Rabu","Kamis","Jumat","Sabtu"],
				namesAbbr: ["Minggu","Sen","Sel","Rabu","Kamis","Jumat","Sabtu"],
				namesShort: ["M","S","S","R","K","J","S"]
			},
			months: {
				names: ["Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","Nopember","Desember",""],
				namesAbbr: ["Jan","Feb","Mar","Apr","Mei","Jun","Jul","Agust","Sep","Okt","Nop","Des",""]
			},
			AM: null,
			PM: null,
			patterns: {
				d: "dd/MM/yyyy",
				D: "dd MMMM yyyy",
				t: "H:mm",
				T: "H:mm:ss",
				f: "dd MMMM yyyy H:mm",
				F: "dd MMMM yyyy H:mm:ss",
				M: "dd MMMM",
				Y: "MMMM yyyy"
			}
		}
	},
	messages: {
	    "Connection": "Koneksi",
    "Defaults": "Konfigurasi Dasar",
    "Login": "Masuk",
    "File": "File",
    "Exit": "Keluar",
    "Help": "Tolong",
    "About": "Tentang",
    "Host": "Pusat",
    "Database": "Database",
    "User": "ID Pengguna",
    "EnterUser": "Masukkan ID pengguna",
    "Password": "Kata Sandi",
    "EnterPassword": "Masukkan kata sandi applikasi",
    "Language": "Pilihan Bahasa",
    "SelectLanguage": "Pilihlah bahasa yang disukai",
    "Role": "Jabatan",
    "Client": "Klien",
    "Organization": "Organisasi",
    "Date": "Tanggal",
    "Warehouse": "Gudang",
    "Printer": "Pencetak",
    "Connected": "Sistem telah terkoneksi",
    "NotConnected": "Sistem tidak terkoneksi!",
    "DatabaseNotFound": "Database tidak ditemukan!",
    "UserPwdError": "Nama ID pengguna anda tidak sesuai dengan kata sandi",
    "RoleNotFound": "Jabatan tidak ditemukan",
    "Authorized": "Anda telah diotorisasi",
    "Ok": "Ok",
    "Cancel": "Batal",
    "VersionConflict": "Konflik Versi",
    "VersionInfo": "Info Versi",
    "PleaseUpgrade": "Mohon hubungi partner Compiere anda untuk upgrade",


    //New Resource

    "Back": "kembali",
    "SelectRole": "Pilih Peran",
    "SelectOrg": "Pilih Organisasi",
    "SelectClient": "Pilih Klien",
    "SelectWarehouse": "Pilih Gudang",
    "VerifyUserLanguage": "Verifikasi Bahasa Pengguna",
    "LoadingPreference": "Loading Preference",
    "Completed": "selesai",
    "RememberMe": "Ingat Saya",
	}
});

}( this ));
