/*
 * Globalize Culture bg-BG
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "bg-BG", "default", {
	name: "bg-BG",
	englishName: "Bulgarian (Bulgaria)",
	nativeName: "български (България)",
	language: "bg",
	numberFormat: {
		",": " ",
		".": ",",
		negativeInfinity: "- безкрайност",
		positiveInfinity: "+ безкрайност",
		percent: {
			",": " ",
			".": ","
		},
		currency: {
			pattern: ["-n $","n $"],
			",": " ",
			".": ",",
			symbol: "лв."
		}
	},
	calendars: {
		standard: {
			"/": ".",
			firstDay: 1,
			days: {
				names: ["неделя","понеделник","вторник","сряда","четвъртък","петък","събота"],
				namesAbbr: ["нед","пон","вт","ср","четв","пет","съб"],
				namesShort: ["н","п","в","с","ч","п","с"]
			},
			months: {
				names: ["януари","февруари","март","април","май","юни","юли","август","септември","октомври","ноември","декември",""],
				namesAbbr: ["ян","февр","март","апр","май","юни","юли","авг","септ","окт","ноември","дек",""]
			},
			AM: null,
			PM: null,
			eras: [{"name":"след новата ера","start":null,"offset":0}],
			patterns: {
				d: "d.M.yyyy 'г.'",
				D: "dd MMMM yyyy 'г.'",
				t: "HH:mm 'ч.'",
				T: "HH:mm:ss 'ч.'",
				f: "dd MMMM yyyy 'г.' HH:mm 'ч.'",
				F: "dd MMMM yyyy 'г.' HH:mm:ss 'ч.'",
				M: "dd MMMM",
				Y: "MMMM yyyy 'г.'"
			}
		}
	},
	messages: {
	   "Connection":"\u0412\u0440\u044a\u0437\u043a\u0430",
   "Defaults":"\u041f\u043e \u043f\u043e\u0434\u0440\u0430\u0437\u0431\u0438\u0440\u0430\u043d\u0435",
   "Login":"\u0421\u0432\u044a\u0440\u0437\u0432\u0430\u043d\u0435 \u0438 \u043e\u0442\u043e\u0440\u0438\u0437\u0430\u0446\u0438\u044f",
   "File":"\u0424\u0430\u0439\u043b",
   "Exit":"\u0418\u0437\u0445\u043e\u0434",
   "Help":"\u041f\u043e\u043c\u043e\u0449",
   "About":"\u0417\u0430 ..",
   "Host":"\u0421\u044a\u0440\u0432\u0435\u0440",
   "Database":"\u0411\u0430\u0437\u0430 \u0434\u0430\u043d\u043d\u0438",
   "User":"\u041f\u043e\u0442\u0440\u0435\u0431\u0438\u0442\u0435\u043b",
   "EnterUser":"\u0412\u044a\u0432\u0435\u0434\u0435\u0442\u0435 \u043f\u043e\u0442\u0440\u0435\u0431\u0438\u0442\u0435\u043b \u043d\u0430 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0435\u0442\u043e",
   "Password":"\u041f\u0430\u0440\u043e\u043b\u0430",
   "EnterPassword":"\u0412\u044a\u0432\u0435\u0434\u0435\u0442\u0435 \u043f\u0430\u0440\u043e\u043b\u0430 \u0437\u0430 \u043f\u043e\u0442\u0440\u0435\u0431\u0438\u0442\u0435\u043b\u044f \u043d\u0430 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0435\u0442\u043e",
   "Language":"\u0415\u0437\u0438\u043a",
   "SelectLanguage":"\u0418\u0437\u0431\u0435\u0440\u0435\u0442\u0435 \u0412\u0430\u0448\u0438\u044f \u0435\u0437\u0438\u043a",
   "Role":"\u041f\u0440\u0438\u0432\u0438\u043b\u0435\u0433\u0438\u0438",
   "Client":"\u041a\u043b\u0438\u0435\u043d\u0442(\u0445\u043e\u043b\u0434\u0438\u043d\u0433)",
   "Organization":"\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f(\u0444\u0438\u0440\u043c\u0430)",
   "Date":"\u0414\u0430\u0442\u0430",
   "Warehouse":"\u0421\u043a\u043b\u0430\u0434",
   "Printer":"\u041f\u0440\u0438\u043d\u0442\u0435\u0440",
   "Connected":"\u0412\u0440\u044a\u0437\u043a\u0430\u0442\u0430 \u0435 \u043e\u0441\u044a\u0449\u0435\u0441\u0442\u0432\u0435\u043d\u0430",
   "NotConnected":"\u0412\u0440\u044a\u0437\u043a\u0430\u0442\u0430 \u043d\u0435 \u0435 \u043e\u0441\u044a\u0449\u0435\u0441\u0442\u0432\u0435\u043d\u0430",
   "DatabaseNotFound":"\u041b\u0438\u043f\u0441\u0432\u0430 \u0431\u0430\u0437\u0430 \u0434\u0430\u043d\u043d\u0438",
   "UserPwdError":"\u041f\u043e\u0442\u0440\u0435\u0431\u0438\u0442\u0435\u043b\u044f \u0438/\u0438\u043b\u0438 \u043f\u0430\u0440\u043e\u043b\u0430\u0442\u0430 \u0441\u0430 \u0433\u0440\u0435\u0448\u043d\u0438",
   "RoleNotFound":"\u041b\u0438\u043f\u0441\u0432\u0430\u0449\u0438 \u043f\u0440\u0438\u0432\u0438\u043b\u0435\u0433\u0438\u0438",
   "Authorized":"\u041e\u0442\u043e\u0440\u0438\u0437\u0430\u0446\u0438\u044f\u0442\u0430 \u0435 \u0443\u0441\u043f\u0435\u0448\u043d\u0430",
   "Ok":"\u0414\u0430",
   "Cancel":"\u041e\u0442\u043a\u0430\u0437",
   "VersionConflict":"\u041a\u043e\u043d\u0444\u043b\u0438\u043a\u0442 \u043d\u0430 \u0432\u0435\u0440\u0441\u0438\u0438\u0442\u0435:",
   "VersionInfo":"\u0421\u044a\u0440\u0432\u0435\u0440 <> \u041a\u043b\u0438\u0435\u043d\u0442",
   "PleaseUpgrade":"\u041c\u043e\u043b\u044f \u0441\u0442\u0430\u0440\u0442\u0438\u0440\u0430\u0439\u0442\u0435 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u0430 \u0437\u0430 \u043e\u0431\u043d\u043e\u0432\u044f\u0432\u0430\u043d\u0435 \u043d\u0430 \u0432\u0435\u0440\u0441\u0438\u044f\u0442\u0430",

    //New Resource

   "Back":"назад",
   "SelectRole":"Изберете Роля",
   "SelectOrg":"Изберете организация",
   "SelectClient":"Изберете Клиент",
   "SelectWarehouse":"Изберете Склад",
   "VerifyUserLanguage":"Проверка на потребителите и език",

   "LoadingPreference":"Зареждане на предпочитания",
   "Completed": "завършен",
   "RememberMe": "Запомни ме",
	}
});

}( this ));
