/*
 * Globalize Culture zh-TW
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "zh-TW", "default", {
	name: "zh-TW",
	englishName: "Chinese (Traditional, Taiwan)",
	nativeName: "中文(台灣)",
	language: "zh-CHT",
	numberFormat: {
		"NaN": "不是一個數字",
		negativeInfinity: "負無窮大",
		positiveInfinity: "正無窮大",
		percent: {
			pattern: ["-n%","n%"]
		},
		currency: {
			pattern: ["-$n","$n"],
			symbol: "NT$"
		}
	},
	calendars: {
		standard: {
			days: {
				names: ["星期日","星期一","星期二","星期三","星期四","星期五","星期六"],
				namesAbbr: ["週日","週一","週二","週三","週四","週五","週六"],
				namesShort: ["日","一","二","三","四","五","六"]
			},
			months: {
				names: ["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月",""],
				namesAbbr: ["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月",""]
			},
			AM: ["上午","上午","上午"],
			PM: ["下午","下午","下午"],
			eras: [{"name":"西元","start":null,"offset":0}],
			patterns: {
				d: "yyyy/M/d",
				D: "yyyy'年'M'月'd'日'",
				t: "tt hh:mm",
				T: "tt hh:mm:ss",
				f: "yyyy'年'M'月'd'日' tt hh:mm",
				F: "yyyy'年'M'月'd'日' tt hh:mm:ss",
				M: "M'月'd'日'",
				Y: "yyyy'年'M'月'"
			}
		},
		Taiwan: {
			name: "Taiwan",
			days: {
				names: ["星期日","星期一","星期二","星期三","星期四","星期五","星期六"],
				namesAbbr: ["週日","週一","週二","週三","週四","週五","週六"],
				namesShort: ["日","一","二","三","四","五","六"]
			},
			months: {
				names: ["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月",""],
				namesAbbr: ["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月",""]
			},
			AM: ["上午","上午","上午"],
			PM: ["下午","下午","下午"],
			eras: [{"name":"","start":null,"offset":1911}],
			twoDigitYearMax: 99,
			patterns: {
				d: "yyyy/M/d",
				D: "yyyy'年'M'月'd'日'",
				t: "tt hh:mm",
				T: "tt hh:mm:ss",
				f: "yyyy'年'M'月'd'日' tt hh:mm",
				F: "yyyy'年'M'月'd'日' tt hh:mm:ss",
				M: "M'月'd'日'",
				Y: "yyyy'年'M'月'"
			}
		}
	},
	messages: {
	    "Connection": "連線",
	    "Defaults": "內定值",
	    "Login": "登入",
	    "File": "檔案",
	    "Exit": "離開",
	    "Help": "求助",
	    "About": "關於",
	    "Host": "主機",
	    "Database": "資料庫",
	    "User": "使用者",
	    "EnterUser": "登入使用者",
	    "Password": "密碼",
	    "EnterPassword": "登入密碼",
	    "Language": "語言",
	    "SelectLanguage": "選擇的語言",
	    "Role": "角色",
	    "Client": "客戶",
	    "Organization": "組織",
	    "Date": "日期",
	    "Warehouse": "倉庫",
	    "Printer": "印表機",
	    "Connected": "已連線",
	    "NotConnected": "未連線",
	    "DatabaseNotFound": "資料庫不存在",
	    "UserPwdError": "使用者密碼錯誤",
	    "RoleNotFound": "角色不存在",
	    "Authorized": "已授權",
	    "Ok": "沒問題",
	    "Cancel": "取消",
	    "VersionConflict": "版本衝突",
	    "VersionInfo": "版本資訊",
	    "PleaseUpgrade": "請升級",

	    //New Resource

	    "Back": "後退",
	    "SelectRole": "選擇角色",
	    "SelectOrg": "選擇組織",
	    "SelectClient": "選擇客戶",
	    "SelectWarehouse": "選擇倉庫",
	    "VerifyUserLanguage": "確認使用者語言",
	    "LoadingPreference": "載入預設",
	    "Completed": "完成",
	    //new
	    "RememberMe": "記得我",
	}
});

}( this ));
